//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34003
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace simpleClient.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.ImathService")]
    public interface ImathService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ImathService/Plus", ReplyAction="http://tempuri.org/ImathService/PlusResponse")]
        int Plus(int a, int b);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ImathService/Min", ReplyAction="http://tempuri.org/ImathService/MinResponse")]
        int Min(int a, int b);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ImathService/Cross", ReplyAction="http://tempuri.org/ImathService/CrossResponse")]
        int Cross(int a, int b);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ImathService/Div", ReplyAction="http://tempuri.org/ImathService/DivResponse")]
        int Div(int a, int b);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ImathServiceChannel : simpleClient.ServiceReference1.ImathService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ImathServiceClient : System.ServiceModel.ClientBase<simpleClient.ServiceReference1.ImathService>, simpleClient.ServiceReference1.ImathService {
        
        public ImathServiceClient() {
        }
        
        public ImathServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ImathServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ImathServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ImathServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public int Plus(int a, int b) {
            return base.Channel.Plus(a, b);
        }
        
        public int Min(int a, int b) {
            return base.Channel.Min(a, b);
        }
        
        public int Cross(int a, int b) {
            return base.Channel.Cross(a, b);
        }
        
        public int Div(int a, int b) {
            return base.Channel.Div(a, b);
        }
    }
}
